AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EcrRepositoryName:
    Type: String
    Description: Name for the ECR Repository
    Default: 'fire-starter-ecr-repository'

Resources:
  FireStarterEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrRepositoryName