name: Deploy AWS Cloudformation Template

on: push

jobs:
  deploy-cloudformation:
    name: Deploy AWS CloudFormation template
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v3

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: fire-starter-stack
          template: cloudformation/application.yaml
          no-fail-on-empty-changeset: '1'
          capabilities: CAPABILITY_NAMED_IAM
